### PR TITLE
Release/v9.0

### LINKED ISSUE #554: Drop support for Python 3.7
Python 3.7 is not a very popular target. It’s better to start supporting 3.10 now.

### PR DESCRIPTION
**Pull request by desilinguist**
## Changes
- Update version number.
- Make conda package noarch again.
- Update release process document for noarch package and other changes.
- Fix broken link in `index.rst`. 
- Update package manifest to exclude more temporary files.
- Update README with the correct python versions and fix outdated link.
- This finally resolves #554 as there should be no more trace of Python 3.7. 

## Package status

- v9 PyPI package deployed to [TestPyPI](https://test.pypi.org/project/rsmtool/) and [tested successfully](https://github.com/EducationalTestingService/rsmtool-pip-tester/pull/13). 
- v9 conda (noarch) package deployed to [anaconda.org](https://anaconda.org/ets/rsmtool) and [tested successfully](https://github.com/EducationalTestingService/rsmtool-conda-tester/pull/16). 

## How to review
In addition to reviewing the changes in the PR, please try testing various combinations of {pip, conda} x {Linux, macOS} x (3.8, 3.9, 3.10}.

### CODE REVIEW

**Comment by Frost45** [comment]
Since we are dropping support from Python 3.7, I think the installation page in the documentation needs to be fixed too. https://rsmtool.readthedocs.io/en/main/getting_started.html

**Comment by desilinguist** [comment]
> Since we are dropping support for Python 3.7, I think the installation page in the documentation needs to be fixed too. https://rsmtool.readthedocs.io/en/main/getting_started.html

Good catch!

**Review by Frost45 — APPROVED** [review]
Tried the `rsmxval` tutorial on MacOS x {pip, conda} x {3.8, 3.9, 3.10}. Works perfectly! Thank you for doing this 🎉

**Review by mulhod — APPROVED** [review]
Tested `rsmtool`, `rsmeval`, and `rsmxval` with Python 3.8/3.9/3.10 on Linux.

**Pull request merged**
