### PR TITLE
Add wandb to rsmpredict, rsmcompare and rsmsummarize

### PR DESCRIPTION
**Pull request by tamarl08**

### CODE REVIEW

**Comment by desilinguist** [comment]
@tamarl08 I am assuming you tested actual experiments for all three to confirm that the logging works as expected?

**Comment by tamarl08** [comment]
yes, I ran all tutorials with wandb, see the "rsmxxx-tutorial" projects: https://wandb.ai/etslabs/projects

**Comment by desilinguist** [comment]
Hmm, one thing I noticed is that all reports have the name `rsmtool_report` in W&B. Can we fix that and call them `rsmeval_report`, `rsmcompare_report` etc.? Or if that's not possible, let's just call it "HTML report" or something more general?

**Comment by tamarl08** [comment]
@desilinguist good point! I fixed it and reran the tutorials.

**Review by desilinguist — APPROVED** [review]

**Review by desilinguist — APPROVED** [review]

**Pull request merged**
