### PR TITLE
v8.1.1 Release

### PR DESCRIPTION
**Pull request by Frost45**
- Updated version number.
- Updated release docs.

### CODE REVIEW

**Comment by desilinguist** [comment]
Can we also test the conda package locally on the servers or our macs? @mulhod @aloukina ?

**Comment by mulhod** [comment]
I have confirmed that it can be installed into an environment on my mac. Without providing the version number, it gets 8.1.1.

**Comment by desilinguist** [comment]
@mulhod can you please run one of the tests to make sure it imports and runs properly?

**Comment by mulhod** [comment]
Yeah, no problems running the tests that I tried after cloning the repo and using the environment.

**Review by mulhod — APPROVED** [review]

**Review by desilinguist — APPROVED** [review]
Excellent work @Frost45!

**Pull request merged**
